### ISSUE TITLE
Descriptionにプロジェクトの説明が書かれていない

### ISSUE THREAD

**Issue by nishio** [IAMAS/makeathon_agreement#8]
とても有益なプロジェクトだと思います。

しかしDescriptionに「`アンケートにご協力ください☞ https://docs.google.com/forms/…`」と書かれているため、ページのtitleが「IAMAS/makeathon_agreement: アンケートにご協力ください☞」になり、Facebookなどで言及した際にアンケートページのように見えます。Descriptionにはプロジェクトの説明を簡潔に書くことが期待されていると思います。

例: https://gyazo.com/be40b4dd89c7c3099eee368c586d9975

**Comment by kotobuki** [comment]
@nishio 
ご指摘の通り、公開当初にアンケートを求めていたときの内容のままになっておりましたので、更新したいと思います。ありがとうございました。

**Comment by kotobuki** [comment]
@nishio その節はご指摘ありがとうございました。遅くなってしまいましたが、説明を更新いたしました。英文版も追加いたしましたので、もし機会がありましたらご活用いただければ幸いです。
